# Generated by Django 6.0.4 on 2026-04-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_membershipinvitation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="membershipinvitation",
            new_name="users_membe_project_b7971f_idx",
            old_name="users_membe_project_ef6d17_idx",
        ),
    ]
