# Generated by Django 6.0.4 on 2026-04-30 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_project_memberships(apps, schema_editor):
    """Create project memberships from legacy project group users."""

    Project = apps.get_model("projects", "Project")
    ProjectMembership = apps.get_model("projects", "ProjectMembership")

    for project in Project.objects.select_related("group").all():
        if project.group_id is None:
            continue

        users = list(project.group.user_set.order_by("id"))
        for index, user in enumerate(users):
            role = "admin" if index == 0 else "member"
            ProjectMembership.objects.get_or_create(
                user=user,
                project=project,
                defaults={"role": role},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Project Admin"),
                            ("member", "Project Member"),
                            ("reader", "Project Reader"),
                        ],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project__name", "user__username"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="projects.ProjectMembership",
                through_fields=("project", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "role"], name="projects_pr_project_33946c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["user", "project"], name="projects_pr_user_id_116009_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "project"),
                name="projects_membership_unique_user_project",
            ),
        ),
        migrations.RunPython(backfill_project_memberships, migrations.RunPython.noop),
    ]
