# Generated by Django 6.0.4 on 2026-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_sourceconfig_plugin_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_cross_newsletter",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_duplicate",
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_engagement",
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_feedback",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_mention",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_recency",
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name="projectconfig",
            name="authority_weight_source_quality",
            field=models.FloatField(default=0.15),
        ),
    ]
