[pytest]
DJANGO_SETTINGS_MODULE = digest_engine.settings
addopts = --disable-plugin-autoload --import-mode=importlib -p pytest_django.plugin -p pytest_mock
python_files = test_*.py
testpaths =
    content/tests
    core/tests
    entities/tests
    ingestion/tests
    newsletters/tests
    pipeline/tests
    projects/tests
    tests
    trends/tests
    users/tests
