# Generated by Django 6.0.4 on 2026-04-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_name", models.CharField(choices=[("rss", "RSS"), ("reddit", "Reddit")], max_length=64)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_configs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["plugin_name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="sourceconfig",
            index=models.Index(fields=["tenant", "plugin_name", "is_active"], name="core_source_tenant__b8437a_idx"),
        ),
    ]
