# Generated by Django 6.0.4 on 2026-04-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_blueskycredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="canonical_url",
            field=models.URLField(blank=True, db_index=True, default=""),
        ),
        migrations.AddField(
            model_name="content",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="core.content",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="duplicate_signal_count",
            field=models.IntegerField(default=0),
        ),
    ]
