# Generated by Django 6.0.4 on 2026-04-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_content_canonical_url_content_duplicate_of_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "suggested_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("vendor", "Vendor"),
                            ("organization", "Organization"),
                        ],
                        max_length=32,
                    ),
                ),
                ("occurrence_count", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_seen_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_candidates",
                        to="core.content",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_entity_candidates",
                        to="core.entity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_candidates",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurrence_count", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "status", "occurrence_count"],
                        name="core_entity_project_4c32ec_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "name"),
                        name="core_entitycandidate_unique_project_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("subject", "Subject"),
                            ("quoted", "Quoted"),
                            ("mentioned", "Mentioned"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("span", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mentions",
                        to="core.content",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="core.entity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mentions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "created_at"],
                        name="core_entity_entity__8ba01e_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="core_entity_project_dabde7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "entity", "role"),
                        name="core_entitymention_unique_content_entity_role",
                    )
                ],
            },
        ),
    ]
