# Generated by Django 6.0.4 on 2026-04-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_entitycandidate_entitymention"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityAuthoritySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("mention_component", models.FloatField()),
                ("feedback_component", models.FloatField()),
                ("duplicate_component", models.FloatField()),
                ("decayed_prior", models.FloatField()),
                ("final_score", models.FloatField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_snapshots",
                        to="core.entity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_authority_snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["entity", "-computed_at"],
                        name="core_entity_entity__9fe820_idx",
                    ),
                    models.Index(
                        fields=["project", "-computed_at"],
                        name="core_entity_project_a31e41_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="content",
            name="authority_adjusted_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["project", "-authority_adjusted_score"],
                name="core_conten_project_44fd9d_idx",
            ),
        ),
    ]
