from typing import Protocol


class CoreSettings(Protocol):
    BLUESKY_CREDENTIALS_ENCRYPTION_KEY: str
    CELERY_TASK_ALWAYS_EAGER: bool
    DEFAULT_FROM_EMAIL: str
    LINKEDIN_CLIENT_ID: str
    LINKEDIN_CLIENT_SECRET: str
    LINKEDIN_CREDENTIALS_ENCRYPTION_KEY: str
    LINKEDIN_OAUTH_SCOPES: str
    METRICS_TOKEN: str
    NEWSLETTER_API_BASE_URL: str
    QDRANT_URL: str
    EMBEDDING_MODEL: str
    EMBEDDING_PROVIDER: str
    EMBEDDING_TRUST_REMOTE_CODE: bool
    OLLAMA_URL: str
    OPENROUTER_API_KEY: str
    OPENROUTER_API_BASE: str
    OPENROUTER_APP_URL: str
    OPENROUTER_APP_NAME: str
    RESEND_API_KEY: str
