apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digest-engine-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/webstackdev/digest-engine.git
    targetRevision: main
    path: deploy/helm/digest-engine
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: digest-engine-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true