# Generated by Django 6.0.4 on 2026-05-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_content_newsletter_promotion"),
        ("entities", "0002_alter_entitycandidate_first_seen_in_and_more"),
        ("projects", "0007_alter_sourceconfig_plugin_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitycandidate",
            name="auto_promotion_blocked_reason",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="entitycandidate",
            name="cluster_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="entitycandidate",
            name="contextual_embedding_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EntityCandidateEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_plugin", models.CharField(max_length=64)),
                ("context_excerpt", models.TextField(blank=True)),
                (
                    "identity_surface",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("bluesky", "Bluesky"),
                            ("mastodon", "Mastodon"),
                            ("website", "Website"),
                        ],
                        max_length=32,
                    ),
                ),
                ("claim_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="entities.entitycandidate",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_candidate_evidence",
                        to="content.content",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_candidate_evidence",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "core_entitycandidateevidence",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "source_plugin"],
                        name="core_entcand_candsrc_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="core_entcand_projtime_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "content"),
                        name="core_entitycandidateevidence_unique_candidate_content",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityIdentityClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("bluesky", "Bluesky"),
                            ("mastodon", "Mastodon"),
                            ("website", "Website"),
                        ],
                        max_length=32,
                    ),
                ),
                ("claim_url", models.URLField()),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_method", models.CharField(blank=True, max_length=64)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_claims",
                        to="entities.entity",
                    ),
                ),
            ],
            options={
                "db_table": "core_entityidentityclaim",
                "ordering": ["surface", "claim_url"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "surface", "claim_url"),
                        name="core_entityidentityclaim_unique_entity_surface_url",
                    )
                ],
            },
        ),
    ]
