# Generated by Django 6.0.4 on 2026-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_entitycandidate_auto_promotion_blocked_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityauthoritysnapshot",
            name="cross_newsletter_component",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entityauthoritysnapshot",
            name="engagement_component",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entityauthoritysnapshot",
            name="recency_component",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entityauthoritysnapshot",
            name="source_quality_component",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="entityauthoritysnapshot",
            name="weights_at_compute",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
