apiVersion: v1
kind: Service
metadata:
  name: {{ include "digest-engine.djangoHost" . }}
  labels:
    {{- include "digest-engine.labels" . | nindent 4 }}
    {{- include "digest-engine.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "django") | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.django.port }}
      targetPort: http
  selector:
    {{- include "digest-engine.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "django") | nindent 4 }}
