{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "digest-engine.fullname" . }}-taskiq-worker
  labels:
    {{- include "digest-engine.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "digest-engine.fullname" . }}-taskiq-worker
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ include "digest-engine.rabbitmqUrl" . | quote }}
        protocol: amqp
        queueName: {{ .Values.keda.queueName | quote }}
        mode: QueueLength
        value: "5"
{{- end }}
