{{- if .Values.jobs.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "newsletter-maker.fullname" . }}-migrate
  labels:
    {{- include "newsletter-maker.labels" . | nindent 4 }}
  {{- if .Values.jobs.migrate.hook }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "newsletter-maker.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "migrate") | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          env:
            - name: BOOTSTRAP_APP
              value: "false"
          envFrom:
            - configMapRef:
                name: {{ include "newsletter-maker.fullname" . }}-env
            - secretRef:
              name: {{ include "newsletter-maker.secretName" . }}
{{- end }}
