apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newsletter-maker.fullname" . }}-nginx
  labels:
    {{- include "newsletter-maker.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        client_max_body_size 20m;

        location / {
            proxy_pass http://{{ include "newsletter-maker.djangoHost" . }}:{{ .Values.django.port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }
