{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newsletter-maker.databaseHost" . }}
  labels:
    {{- include "newsletter-maker.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
  selector:
    {{- include "newsletter-maker.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "postgres") | nindent 4 }}
{{- end }}
