{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newsletter-maker.redisHost" . }}
  labels:
    {{- include "newsletter-maker.labels" . | nindent 4 }}
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "newsletter-maker.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "redis") | nindent 4 }}
{{- end }}
