{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "newsletter-maker.redisHost" . }}
  labels:
    {{- include "newsletter-maker.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "newsletter-maker.redisHost" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "newsletter-maker.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "newsletter-maker.componentLabels" (dict "Release" .Release "Values" .Values "Chart" .Chart "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
{{- end }}
